version: "3.7"

services:
  proxy:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    links:
      - nest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']

  nest:
    image: kyhsa93/nestjs-rest-cqrs-example
    restart: always
    env_file:
      - .env
    links:
      - database

  redis-master:
    image: kyhsa93/redis-master
    restart: always

  redis-slave:
    image: kyhsa93/redis-slave
    restart: always

  database:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - ~/database/nest:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:alpine
    restart: always
    ports: 
      - 5672:5672
      - 15672:15672
    environment: 
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: test
