name: nest rest cqrs example

on: 
  push:
    paths:
      - src/**
      - .github/workflows/**
    branches:
      - master

jobs:
  node-version-test:
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up nodejs version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install package
      run: npm install
    - name: Test
      run: npm test
  erbium-alpine-test:
    needs: node-version-test
    runs-on: ubuntu-latest
    container:
      image: node:erbium-alpine
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install package
      run: npm install
    - name: Test
      run: npm test
  build-image:
    needs: erbium-alpine-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: build container image
      run: docker build -t kyhsa93/nestjs-rest-cqrs-example:${{ github.sha }} .
    - name: push container image
      run: docker push kyhsa93/nestjs-rest-cqrs-example:${{ github.sha }}
